version: '3'

services:

  controller:
    image: 'trinodb/trino:444'
    hostname: trino
    volumes:
      - ./catalog:/etc/trino/catalog
    ports:
      - '8082:8080'
    depends_on:
      metastore:
        condition: service_healthy
      object-store:
        condition: service_healthy

  object-store:
    image: minio/minio:RELEASE.2024-03-30T09-41-56Z
    environment:
      - MINIO_ROOT_USER=minio-user
      - MINIO_ROOT_PASSWORD=minio-password
    ports:
      - 9001:900
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
    healthcheck:
      test: ["CMD-SHELL", "mc alias set minio http://localhost:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD} && mc mb minio/warehouse && mc anonymous set public minio/warehouse"]
      interval: 2s
      timeout: 2s
      retries: 5

  metastore:
    image: postgres:alpine3.19
    ports:
      - 5432:5432
    volumes:
      - ./iceberg-setup.sql:/docker-entrypoint-initdb.d/iceberg-setup.sql
    environment:
      - POSTGRES_USER=postgres-user
      - POSTGRES_PASSWORD=postgres-password
      - POSTGRES_DB=iceberg
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres-user -d iceberg"]
      interval: 5s
      timeout: 5s
      retries: 5