version: "3.9" 
services:
  oltp:
    image: postgres:latest
    container_name: oltp
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "15432:5432"
    networks:
      kafka:
        ipv4_address: 172.20.0.15   

networks:
  kafka:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16     



